### ISSUE TITLE
🏹👆 : make that arrow interactive

### ISSUE THREAD

**Issue by withrvr** [HarshKapadia2/portfolio-v2#12]
# Problem
- currently non Clickable
- me / user thinking it's clickable
- and clicking again and again
- but nothing happens

![image](https://user-images.githubusercontent.com/69628500/216765338-2dbac507-2808-4061-a70c-26067560d505.png)

# Solution

- which will redirect to 
- the section next to it
- ie. About
- with transition

**Comment by HarshKapadia2** [comment]
Yes, this can be done. Good idea.

Do you want to open a Pull Request for this, @withrvr?

**Comment by withrvr** [comment]
@HarshKapadia2 

y not

and it's very small only
and I will also learn how to contribute

but will do it tomorrow
