### ISSUE TITLE
`/pictures` vs `/pictures.html` link

### ISSUE THREAD

**Issue by withrvr** [HarshKapadia2/portfolio-v2#14]
> I think you did it on purpose

- because `/pictures` work on GitHub pages
- but not locally
- so you have to use `/pictures.html` manually
- when clicking on this link

![image](https://user-images.githubusercontent.com/69628500/216811018-957f0092-dabc-421a-99f8-aa93611c068d.png) 

### Do you think it should be changed?

- not a big technical / UI / UX bug
- but I came across this
- in case you not noticed it

**Comment by HarshKapadia2** [comment]
Yes, having to modify `/pictures` to `/pictures.html` during development is a little irritating, but `/pictures` looks better in production, so it makes to me to keep it this way.

Thank you for pointing it out though! I appreciate it!
